### ISSUE TITLE
Clear cache will freeze the ps3

### ISSUE THREAD

**Issue by XestoX** [bucanero/apollo-ps3#4] opened 2020-02-18 18:49 UTC
CECHB00

**Comment by bucanero** [comment] 2020-02-18 20:41
can you check the content of the `game/NP0APOLLO/USRDIR/CACHE` folder?

is anything in there? is it empty?

**Comment by bucanero** [comment] 2020-02-20 14:46
weird, I tried many times to reproduce the bug on my side, and I could only make it happen 1 time, but I'm still wondering how it happened. I couldn't reproduce the bug on a consistent manner.

If you have more information on how you got the freeze, that will help on fixing this issue.

**Comment by XestoX** [comment] 2020-02-21 04:15
> can you check the content of the `game/NP0APOLLO/USRDIR/CACHE` folder?
> 
> is anything in there? is it empty?

In there is a games.txt and a ver.check. I got a CECH B 00 with 4.84 Rebug REX. WebManMod running. always when I hit delete cache my ps3 freezs without auto rebootm just stuck. but i can turn it of with the touch ower button no power brick reset needed. after that i always got a broken file system and have to wait 20 minutes. (1TB drive installed.) Its latest apollo version.

**Comment by bucanero** [comment] 2020-02-21 12:36
thanks for the info. Clearly it's getting stuck when trying to delete those files (`games.txt` , `ver.check`)

the "clear local cache" function is simple, so the bug is limited to deleting files in that dir. I have a few ideas for a fix, but since I can't properly reproduce it on my HEN ps3, would you mind helping by testing a few beta-builds to see if it fixes the issue?

I would send you an EBOOT.BIN that you can just copy over the current Apollo version and check if it doesn't get stuck when clearing the cache

**Comment by XestoX** [comment] 2020-02-21 17:23
> thanks for the info. Clearly it's getting stuck when trying to delete those files (`games.txt` , `ver.check`)
> 
> the "clear local cache" function is simple, so the bug is limited to deleting files in that dir. I have a few ideas for a fix, but since I can't properly reproduce it on my HEN ps3, would you mind helping by testing a few beta-builds to see if it fixes the issue?
> 
> I would send you an EBOOT.BIN that you can just copy over the current Apollo version and check if it doesn't get stuck when clearing the cache

sure, it would be a honor to help you improve this awesome tool :) send me over the files I need :) ( But I can not promise to always test it imidiatly. I often have to work a week in other countrys/towns and don't get home for days so often it took some time for me to reply.)

I got also other ps3 models where I can test it. I got in my collection like allready mentioned the PS3 B00 but further that I got also a CECH-/C04/L04/2504 and a 4004 on HEN all CFW PS3's are on Rebug Rex 4.84, the 4004 hen is on latest hen.

I guess if you do not get the error on hen I woun't ether but I could test all consoles If you like to, just say if you need it :)

I don't think the ps3 hardware model make such a difference on this kind of tool, but there are some HW issues for example in the L PS3 with webmanmod. always when you do a hardreset the ps3 fan goes totaly insane and slowes down slowly, was never fixed.
this is only when using alternate fan control an ONLY on L model ps3's. So with apollo I guess it could be a problem with this early PS3 modells and apollo. but I don't know I only understand total basics in programming languages. im just simple IT technician :D

**Comment by XestoX** [comment] 2020-02-21 17:32
UPDATE: I now tried it a third time to clear the cache, now nothing crached. Checked the folder and everything is deleted. seems to be some kind of sporadically bug. or anythign to do with previously loaded webman mod temp display or artemis cheats. I wil ltest out apollo after i played Silent Hill with artemis cheats for some hours and use webmn mod a bit and g oback to apollo to test if this got some incomapatebilitys with that often my ps3's craches in normaly working tools and games AFTER the use of webman or artemis. My B model ps3 often showes the Overheating LED after i turned it of after the use of artemis/webmanmod, also some strange. my PS3's are all delited and never gets over 65°C there never got overheated.

**Comment by bucanero** [comment] 2020-02-23 12:50
weird, but it matches my experience, where I could only reproduce the bug once, and then every other time I tried the `clear local cache` option, it worked just fine.

my guess is that some file in the "CACHE" folder might be in use or open, and then it gets stuck waiting for the file to be deleted. Still, I don't know the real source of the issue and I'm only guessing.

**Comment by bucanero** [comment] 2020-02-26 22:29
by chance, I saw a youtube video about Apollo and the user was also saying that the "clear local cache" option will freeze your PS3.

I'll probably remove the function on the next release, at least until this bug can be properly identified and debugged.

**Comment by bucanero** [comment] 2020-03-05 12:45
I finally found the reason behind this bug. It was not related to the file deletion, but to the UI.
If you pressed **X** it worked, but if you used `left` or `right` the UI crashed due to a `null` reference.

Fix will be available in the next release.

**Comment by bucanero** [comment] 2020-03-07 00:42
Fixed in https://github.com/bucanero/apollo-ps3/commit/04658239964517e907135dbe8a6e25f03f697c63

**Closed by bucanero** 2020-03-07 00:42 UTC
Labels: bug
